# Generated by Django 2.2.24 on 2021-08-16 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('text', models.TextField(max_length=10000, verbose_name='Основной текст')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('status', models.IntegerField(choices=[(0, 'Не опубликован'), (1, 'Опубликован')], default=0, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_on'],
            },
        ),
    ]
