# Generated by Django 2.2.24 on 2021-09-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210902_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='login',
            field=models.EmailField(default='pashkan', max_length=254, unique=True, verbose_name='Логин'),
            preserve_default=False,
        ),
    ]
