# Generated by Django 2.2.24 on 2021-09-03 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='login',
        ),
    ]
