# Generated by Django 2.2.24 on 2021-09-06 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='text',
        ),
        migrations.AddField(
            model_name='office',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='office',
            name='coordinates',
            field=models.CharField(max_length=255, null=True, verbose_name='Координаты'),
        ),
        migrations.AddField(
            model_name='office',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='office',
            name='phone',
            field=models.CharField(max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='office',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_of_city', to='calculator.City'),
        ),
    ]
