# Generated by Django 2.2.24 on 2021-09-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_auto_20210906_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='office',
            name='coordinate1',
            field=models.DecimalField(decimal_places=9, max_digits=12, null=True, verbose_name='Координата1'),
        ),
        migrations.AddField(
            model_name='office',
            name='coordinate2',
            field=models.DecimalField(decimal_places=9, max_digits=12, null=True, verbose_name='Координата2'),
        ),
    ]
