# Generated by Django 2.2.24 on 2021-09-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_auto_20210908_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='email',
            field=models.CharField(max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='office',
            name='schedule',
            field=models.CharField(max_length=255, null=True, verbose_name='Режим работы'),
        ),
    ]
