# Generated by Django 2.2.24 on 2021-08-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0003_auto_20210824_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconsignment',
            name='documents',
            field=models.CharField(blank=True, choices=[('Паспорт', 'Паспорт'), ('Заграничный паспорт', 'Заграничный паспорт'), ('Военный билет', 'Военный билет'), ('Водительское удостоверение', 'Водительское удостоверение')], default='Паспорт', max_length=50, null=True, verbose_name='Выберите тип документа'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='documents_p',
            field=models.CharField(blank=True, choices=[('Паспорт', 'Паспорт'), ('Заграничный паспорт', 'Заграничный паспорт'), ('Военный билет', 'Военный билет'), ('Водительское удостоверение', 'Водительское удостоверение')], default='Паспорт', max_length=50, null=True, verbose_name='Выберите тип документа'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='email_entity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='email_entity_p',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='email_individual',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='email_individual_p',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='height_one',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.1, max_digits=7, null=True, verbose_name='Высота(м)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='length_one',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.1, max_digits=7, null=True, verbose_name='Длина(м)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='reimbursement_method',
            field=models.CharField(blank=True, choices=[('По чеку на адресе', 'По чеку на адресе'), ('Включить в счет', 'Включить в счет')], default='Включить в счет', max_length=50, null=True, verbose_name='Способ возмещения суммы'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='some_highest',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.1, max_digits=7, null=True, verbose_name='Самое высокое(м)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='some_longest',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.1, max_digits=7, null=True, verbose_name='Самое длинное(м)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='some_place_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, default=2, max_digits=7, null=True, verbose_name='Кол-во мест'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='some_volume',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.001, max_digits=7, null=True, verbose_name='Общий объем(м3)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='some_weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.1, max_digits=7, null=True, verbose_name='Общий вес(кг)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='some_widest',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.1, max_digits=7, null=True, verbose_name='Самое широкое(м)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='volume_one',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.001, max_digits=8, null=True, verbose_name='Объем(м3)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='weight_one',
            field=models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=7, null=True, verbose_name='Вес(кг)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='width_one',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.1, max_digits=7, null=True, verbose_name='Ширина(м)'),
        ),
    ]
