# Generated by Django 2.2.24 on 2021-08-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0004_auto_20210824_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconsignment',
            name='cod_input',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма наложенного платежа'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма'),
        ),
    ]
