# Generated by Django 2.2.24 on 2021-08-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0006_auto_20210825_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconsignment',
            name='air_bubble_amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Укажите количество'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='bag_amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Укажите количество'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='cardboard_box_amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Укажите количество'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='pallet_amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Укажите количество'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='pallet_board_amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Укажите количество'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='rigid_packaging_amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Укажите количество'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='strapping_amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Укажите количество'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='stretch_amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Укажите количество'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='interval2',
            field=models.CharField(choices=[('7:00', '7:00'), ('8:00', '8:00'), ('9:00', '9:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00'), ('22:00', '22:00'), ('23:00', '23:00')], default='18:00', max_length=50, verbose_name='Время доставки, до'),
        ),
    ]
