# Generated by Django 2.2.24 on 2021-08-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0009_orderconsignment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconsignment',
            name='category',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=20),
        ),
    ]
