# Generated by Django 2.2.24 on 2021-08-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0011_auto_20210831_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconsignment',
            name='category',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=20, null=True),
        ),
    ]
