# Generated by Django 2.2.24 on 2021-08-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0012_auto_20210831_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconsignment',
            name='category',
            field=models.CharField(blank=True, choices=[('p1', 'p1'), ('p2', 'p2'), ('d', 'd')], default='p1', max_length=20, null=True),
        ),
    ]
