# Generated by Django 2.2.24 on 2021-08-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0013_auto_20210831_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconsignment',
            name='category',
            field=models.CharField(blank=True, default='1place', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='date_cargo',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата забора груза'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='nature_cargo',
            field=models.CharField(max_length=255, null=True, verbose_name='Характер груза'),
        ),
    ]
