# Generated by Django 2.2.24 on 2021-08-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0014_auto_20210831_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconsignment',
            name='date_cargo',
            field=models.DateField(blank=True, null=True, verbose_name='Дата забора груза'),
        ),
    ]
