# Generated by Django 2.2.24 on 2021-08-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0015_auto_20210831_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconsignment',
            name='city_from',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Откуда'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='city_to',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Куда'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='nature_cargo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Характер груза'),
        ),
    ]
