# Generated by Django 2.2.24 on 2021-08-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0016_auto_20210831_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconsignment',
            name='height_one',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.1, max_digits=8, null=True, verbose_name='Высота(м)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='length_one',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.1, max_digits=8, null=True, verbose_name='Длина(м)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='weight_one',
            field=models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=8, null=True, verbose_name='Вес(кг)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='width_one',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.1, max_digits=8, null=True, verbose_name='Ширина(м)'),
        ),
    ]
