# Generated by Django 2.2.24 on 2021-08-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0017_auto_20210831_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconsignment',
            name='some_highest',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.1, max_digits=8, null=True, verbose_name='Самое высокое(м)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='some_longest',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.1, max_digits=8, null=True, verbose_name='Самое длинное(м)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='some_place_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, default=2, max_digits=8, null=True, verbose_name='Кол-во мест'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='some_volume',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.001, max_digits=8, null=True, verbose_name='Общий объем(м3)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='some_weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.1, max_digits=8, null=True, verbose_name='Общий вес(кг)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='some_widest',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.1, max_digits=8, null=True, verbose_name='Самое широкое(м)'),
        ),
    ]
