# Generated by Django 2.2.24 on 2021-09-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0018_auto_20210831_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconsignment',
            name='carry_recipient',
            field=models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=7, null=True, verbose_name='Пронос(м)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='carry_sender',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5, null=True, verbose_name='Пронос(м)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='floor_recipient',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Поднятие(этаж)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='floor_sender',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Поднятие(этаж)'),
        ),
    ]
