# Generated by Django 2.2.24 on 2021-09-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0019_auto_20210901_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconsignment',
            name='declared_value',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Объявленная стоимость'),
        ),
    ]
