# Generated by Django 2.2.24 on 2021-09-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0020_auto_20210902_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconsignment',
            name='carry_recipient',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Пронос(м)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='carry_sender',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Пронос(м)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='floor_recipient',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Поднятие(этаж)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='floor_sender',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Поднятие(этаж)'),
        ),
    ]
