# Generated by Django 2.2.24 on 2021-09-06 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0022_auto_20210902_1618'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cities',
        ),
    ]
