# Generated by Django 2.2.24 on 2021-09-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0024_orderconsignment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconsignment',
            name='date_of_order',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата заказа'),
        ),
    ]
