# Generated by Django 2.2.24 on 2021-09-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0026_auto_20210907_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconsignment',
            name='cardboard_box_amount',
            field=models.PositiveIntegerField(default=1, verbose_name='0,2 х 0,19 х  0,13 м. Укажите количество'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='cardboard_box_amount_100',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='0,3 х 0,26 х 0,38 м. Укажите количество'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='cardboard_box_amount_70',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='0,3 х 0,25 х 0,17 м. Укажите количество'),
        ),
    ]
