# Generated by Django 2.2.24 on 2021-09-08 07:54

import common.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0028_auto_20210908_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconsignment',
            name='num',
            field=common.utils.OrderField(blank=True, null=True),
        ),
    ]
