# Generated by Django 2.2.24 on 2021-09-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0030_remove_orderconsignment_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconsignment',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Цена'),
        ),
    ]
