# Generated by Django 2.2.24 on 2021-09-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0031_orderconsignment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconsignment',
            name='reimbursement_method',
            field=models.CharField(choices=[('По чеку на адресе', 'По чеку на адресе'), ('Включить в счет', 'Включить в счет')], default='Включить в счет', max_length=50, verbose_name='Способ возмещения суммы'),
        ),
    ]
