# Generated by Django 2.2.24 on 2021-09-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0032_auto_20210908_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconsignment',
            name='some_place_quantity',
            field=models.PositiveIntegerField(blank=True, default=2, null=True, verbose_name='Кол-во мест'),
        ),
    ]
