# Generated by Django 2.2.24 on 2021-09-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0033_auto_20210909_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderconsignment',
            name='recipient_customer',
        ),
        migrations.RemoveField(
            model_name='orderconsignment',
            name='sender_customer',
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='recipient_payer',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='sender_payer',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Отправитель'),
        ),
    ]
