# Generated by Django 2.2.24 on 2021-09-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0034_auto_20210910_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconsignment',
            name='contact_person_entity_p_for_third_side',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='contact_person_entity_s_for_third_side',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='documents_p_for_third_side',
            field=models.CharField(blank=True, choices=[('Паспорт', 'Паспорт'), ('Заграничный паспорт', 'Заграничный паспорт'), ('Военный билет', 'Военный билет'), ('Водительское удостоверение', 'Водительское удостоверение')], default='Паспорт', max_length=50, null=True, verbose_name='Выберите тип документа'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='documents_s_for_third_side',
            field=models.CharField(blank=True, choices=[('Паспорт', 'Паспорт'), ('Заграничный паспорт', 'Заграничный паспорт'), ('Военный билет', 'Военный билет'), ('Водительское удостоверение', 'Водительское удостоверение')], default='Паспорт', max_length=50, null=True, verbose_name='Выберите тип документа'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='email_entity_p_for_third_side',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='email_entity_s_for_third_side',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='email_individual_p_for_third_side',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='email_individual_s_for_third_side',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='fio_entity_p_for_third_side',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='fio_entity_s_for_third_side',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='fio_individual_p_for_third_side',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='fio_individual_s_for_third_side',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='inn_entity_p_for_third_side',
            field=models.IntegerField(blank=True, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='inn_entity_s_for_third_side',
            field=models.IntegerField(blank=True, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='passport_individual_p_for_third_side',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Серия и номер выбранного документа'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='passport_individual_s_for_third_side',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Серия и номер выбранного документа'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='phone_entity_p_for_third_side',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Контактный телефон'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='phone_entity_s_for_third_side',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Контактный телефон'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='phone_individual_p_for_third_side',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Контактный телефон'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='phone_individual_s_for_third_side',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Контактный телефон'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='comment',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Комментарий к заказу'),
        ),
    ]
