# Generated by Django 2.2.24 on 2021-09-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0035_auto_20210914_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconsignment',
            name='air_bubble_amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Укажите количество'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='pallet_board_amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Укажите количество'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='passport_individual',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Серия и номер документа'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='passport_individual_p',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Серия и номер документа'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='passport_individual_p_for_third_side',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Серия и номер документа'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='passport_individual_s_for_third_side',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Серия и номер документа'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='rigid_packaging_amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Укажите количество'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='strapping_amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Укажите количество'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='stretch_amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Укажите количество'),
        ),
    ]
