# Generated by Django 2.2.24 on 2021-09-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0037_auto_20210920_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconsignment',
            name='type_transporation',
            field=models.CharField(choices=[('null', ''), ('Стандарт', 'Стандарт'), ('Экспресс', 'Экспресс'), ('Конверт', 'Конверт')], default='Стандарт', max_length=50, verbose_name='Вид перевозки'),
        ),
    ]
