# Generated by Django 2.2.24 on 2021-08-17 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_standart_from', models.IntegerField()),
                ('term_standart_to', models.IntegerField()),
                ('term_express_from', models.IntegerField()),
                ('term_express_to', models.IntegerField()),
                ('cityfrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_cityfrom', to='calculator.City')),
                ('cityto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_cityto', to='calculator.City')),
            ],
        ),
        migrations.CreateModel(
            name='Calculate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weightfrom', models.DecimalField(decimal_places=2, max_digits=9)),
                ('weightto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('inter_terminal', models.IntegerField()),
                ('delivery_from', models.IntegerField()),
                ('delivery_to', models.IntegerField()),
                ('cityfrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calc_cityfrom', to='calculator.City')),
                ('cityto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calc_cityto', to='calculator.City')),
            ],
        ),
    ]
