# Generated by Django 2.2.24 on 2021-08-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculate',
            name='convert_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
