# Generated by Django 2.2.24 on 2021-09-06 11:13

import common.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_auto_20210906_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='order',
            field=common.utils.OrderField(blank=True, null=True),
        ),
    ]
