# Generated by Django 2.2.24 on 2021-09-22 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_city_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='order',
        ),
        migrations.AlterField(
            model_name='calculate',
            name='cityfrom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_cityfrom', to='calculator.City'),
        ),
        migrations.AlterField(
            model_name='calculate',
            name='cityto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_cityto', to='calculator.City'),
        ),
    ]
