# Generated by Django 2.2.24 on 2021-08-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trek', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('status_date', models.DateField(auto_now_add=True)),
                ('status_payment', models.CharField(max_length=200)),
                ('direction', models.CharField(max_length=500)),
            ],
        ),
    ]
