# Generated by Django 2.2.24 on 2021-08-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracking',
            old_name='direction',
            new_name='route',
        ),
        migrations.RenameField(
            model_name='tracking',
            old_name='status_payment',
            new_name='tracking_number_client',
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='trek',
        ),
        migrations.AddField(
            model_name='tracking',
            name='status_pay',
            field=models.CharField(choices=[('paid', 'ОПЛАЧЕНО'), ('not_paid', 'НЕ ОПЛАЧЕНО')], default='Уточняется', max_length=50),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='status',
            field=models.CharField(choices=[('In_awaiting_of_delivering_cargo', 'ОЖИДАЕТСЯ ДОСТАВКА ГРУЗА'), ('Accepted_on_sklad_otpravki', 'ПРИНЯТО НА СКЛАД ОТПРАВКИ'), ('In_expecting_0f_otpravka', 'ОЖИДАЕТСЯ ОТПРАВКА'), ('V_puti', 'В ПУТИ'), ('Pribilo_na_sklad_poluchenia', 'ПРИБЫЛО НА СКЛАД ПОЛУЧЕНИЯ'), ('Gotovo_k_vidache', 'ГОТОВО К ВЫДАЧЕ'), ('Vidano', 'ВЫДАНО'), ('Pribilo_na_sklad_tranzita', 'ПРИБЫЛО НА СКЛАД ТРАНЗИТА')], default='Уточняется', max_length=50),
        ),
    ]
