# Generated by Django 2.2.24 on 2021-09-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20210818_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
    ]
